version: '3.5'
services:

  contacorrente:
    container_name: app-contacorrente
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8083:8083'
    networks:
      - net-driver
      - eureka_net-driver
      - credito_net-driver
      - debito_net-driver
    external_links:
      - eureka:eureka
      - credito:credito
      - debito:debito
    depends_on:
      - db
    links:
      - db
    restart: on-failure

  db:
    image: mysql
    container_name: dbcontacorrente
    hostname: dbcontacorrente
    restart: always
    networks:
      - net-driver
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contacorrentedb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

networks:
  net-driver:
    driver: bridge
  eureka_net-driver:
    external: true
  credito_net-driver:
    external: true
  debito_net-driver:
    external: true
