server:
  port : 8083
  error:
    include-message: always
    include-stacktrace: never
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: '${EUREKA_CONNECTION_URL:http://localhost:8761}/eureka'
    fetch-registry: true
    register-with-eureka: true
spring:
  application:
    name: conta-corrente
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: '${DATABASE_CONNECTION_URL:jdbc:mysql://localhost:3306/contacorrentedb}'
    username: mysql
    password: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: update
        show-sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

clients:
  credito: '${CREDITO_URL:http://localhost:8081/credito}'
  debito: '${DEBITO_URL:http://localhost:8082/debito}'